sudo: false
language: node_js
node_js:
- '4.1'
- '4.0'
- '0.12'
- '0.11'
- '0.10'
- iojs
env:
  global:
  - secure: MHWFVzCNT3YgBM9Ns8mGuy28ESrsXTvJAMgd9K99FhqqMC2mRv6DiRUGtjVgi+nlxCl1aEPBAJMHhTin/NnW0hHKIjPetu4rUzkvOkcCjczjVyr0AYhlRcWYsXT7Dh7z5MM+JCPtLjbaJ1aSwKDMJiYfQmOFnxh5RvlGAzG3UTY=
  - secure: J61RQuaBVwcFkZebRGMC8eM7u3B1CJDbXqhTWkHl7yFfQcVDVB0jYTCoF+5K04FKDy66mI+xhuQCI0FXKQ34Ioj/E70tAmAWjqUFD1ywXnMha1C4KZme577PfBvM6Qtl05usYIli3j/oYqifBDtOa4cqf4jQJa1tpa+77WtJ5D4=
  - secure: g6Zv0625Z9ZWzp/AmjfDEiap2nUEvRqHGhcmiWErBpW2c0pyN3rfYsCYz6FGqYX25hF1rmwInZ9ERI0NliP+g9zeq+hEDCkkSNoJccp7rrzzFPdeQ2fNoM2n1A7puNAw8daKv13wHh0k0ZB4thpFA4YOomzuNB0DXejJvC5kHSs=
  - secure: L3eAKCK0W9AbqgN+QlPVzvX1gUhfdPQBm3y0N25Cmt8ZpLDwoiCRSiNqRrgbYlrAKC4fmu7+ZSyepa0QwlKzbF4lzG/4o1Bq9G2uNQjdrtfa1w/8C3lmRd/C9TyWqF7j3Tv8Wjf7CHP4UD76N8XsdByoI8d6Z8so1fxvqCTkuZE=
